t = importdata('D:\matlab\why_magnetic\video0028\t.mat');
xt = importdata('D:\matlab\why_magnetic\video0028\xt.mat');
xt_para = importdata('D:\matlab\why_magnetic\video0028\xt_para.mat');
vt_para = importdata('D:\matlab\why_magnetic\video0028\vt_para.mat');
at_para = importdata('D:\matlab\why_magnetic\video0028\at_para.mat');
t_max = max(t);
ti=0:0.01:t_max;  
xi=polyval(xt_para,ti);  
vi=polyval(vt_para,ti); 
ai=polyval(at_para,ti); 
figure(1);
plot(ti,xi,t,xt,'r.'); 
xlabel('t');ylabel('x');
figure(2);
plot(ti,vi); 
xlabel('t');ylabel('v');
figure(3);
plot(ti,ai); 
xlabel('t');ylabel('a');
figure(4);
plot(xi,ai); 
xlabel('x');ylabel('a');
figure(5);
plot(xi,vi); 
xlabel('x');ylabel('v');
